// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMBax2i83OUg8uSQYDQkhzBR3jO2ybOM8',
    appId: '1:101011406058:web:b4854fdd0ec8be49b0eb93',
    messagingSenderId: '101011406058',
    projectId: 'clone-2c230',
    authDomain: 'clone-2c230.firebaseapp.com',
    storageBucket: 'clone-2c230.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG65RIMXD_imZQ6OHyhEzVkjxoJx4tcic',
    appId: '1:101011406058:android:fb9e0049aaed5a3fb0eb93',
    messagingSenderId: '101011406058',
    projectId: 'clone-2c230',
    storageBucket: 'clone-2c230.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA882pfZivBfkDe-pWXzx8E7IiSGbflPyw',
    appId: '1:101011406058:ios:d89476d4c2f875e3b0eb93',
    messagingSenderId: '101011406058',
    projectId: 'clone-2c230',
    storageBucket: 'clone-2c230.firebasestorage.app',
    iosBundleId: 'omar.app.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA882pfZivBfkDe-pWXzx8E7IiSGbflPyw',
    appId: '1:101011406058:ios:d89476d4c2f875e3b0eb93',
    messagingSenderId: '101011406058',
    projectId: 'clone-2c230',
    storageBucket: 'clone-2c230.firebasestorage.app',
    iosBundleId: 'omar.app.amazonClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMBax2i83OUg8uSQYDQkhzBR3jO2ybOM8',
    appId: '1:101011406058:web:506f6d3625c0f342b0eb93',
    messagingSenderId: '101011406058',
    projectId: 'clone-2c230',
    authDomain: 'clone-2c230.firebaseapp.com',
    storageBucket: 'clone-2c230.firebasestorage.app',
  );
}
